In [90]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# Assuming the dataset is stored in a CSV file named 'qsar_oral_toxicity.csv'
data = pd.read_csv('qsar_oral_toxicity.csv', header=None, sep=";")

data

,0,1,2,3,4,5,6,7,8,9,...,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,negative
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,negative
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8987,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,negative
8988,0,1,0,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,negative
8989,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,negative
8990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
8991,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,negative

In [91]:
# Set the column names
#column_names = ['Attribute' + str(i) for i in range(1, 1025)] + ['Class']
#data.columns = column_names

In [92]:
#data.columns()

In [93]:
X = data.iloc[:, :-1]  # Features (binary molecular fingerprints)
y = data.iloc[:, -1]   # Target variable (experimental class)
y

0       negative
1       negative
2       negative
3       negative
4       negative
          ...
8987    negative
8988    negative
8989    negative
8990    negative
8991    negative
Name: 1024, Length: 8992, dtype: object

In [134]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [140]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

# max_iter due to error message "error message you received is a ConvergenceWarning from scikit-learn's logistic regression implementation. "

In [142]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
4967,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1389,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2501,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4966,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,1,0,0,0,0,0
4360,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
79,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,0
8039,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
6936,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5640,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [143]:
y_train

4967    negative
1389    positive
2501    negative
4966    negative
4360    negative
          ...
350     negative
79      negative
8039    negative
6936    negative
5640    negative
Name: 1024, Length: 7193, dtype: object

In [144]:
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [145]:
y_pred = lr.predict(X_test)
y_pred

array(['negative', 'negative', 'negative', ..., 'negative', 'negative',
       'negative'], dtype=object)

In [146]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

#lr = LogisticRegression(C=1)
#lr.fit(X_train, y_train)
#accuracy_score(y_test, lr.predict(X_test))

Accuracy: 0.9255141745414119

In [147]:
#error_rate
print("test error rate: {:.2f}%".format((1-accuracy)*100))

test error rate: 7.45%

in regards to the LDA/QDA application, it is not suitable to use on this dataset because it is a binary dataset. LDA/QDA method assumes that the predictor follows a Gaussian distribution as Gaussian distribution assumes the variables to be continuous that follow a bell-shaped curve. this is because Gaussian distribution is also referred as normal distribution

thus, in a binary dataset, the value is discrete, and usually it is categorised into 0 and 1. therefore, the discrete data contradicts the continous data required in Gaussian distribution. 

in addition, as Gaussian distribution is characterized by its mean, standard deviation, where majority of the data is concentrated around the mean, this Gaussian distribution that the value of the data can take any value within any real numbers in the range. unlike binary data, there are only two possible values and does not have a continuous range. therefore, it cannot fit adequately into the Gaussian distribution.

furthermore, LDA assumes that the variance of the predictors are equal across for each predictor variable. however it is not the case for this dataset.

In the case of binary molecular fingerprints, logistic regression is a more appropriate choice. Logistic regression can handle binary features and does not assume any particular distribution. It can capture the complex relationships between the binary molecular fingerprints and the experimental class without the need for distributional assumptions.